### PR TITLE
Bug Fixes

### LINKED ISSUE #119: [PE-D] Vague error for missing parameters
When some compulsory param(s) are not provided, for e.g. add withtou any parameters, program gives a vague "Missing or incorrect add statement" without telling the user which parameters are missing.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Artemis-Hunt/ped#4

### LINKED ISSUE #120: [PE-D] Editinfo does not do any validation for the parameter supplied
editinfo allows invalid parameters e.g. "editinfo sd45345". this shows an "updated your personal information" message despite not having made any changes.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Artemis-Hunt/ped#5

### LINKED ISSUE #121: [PE-D] Backslash after parameter tag causes crash
Putting a backslash after a parameter e.g. n//45345 causes a crash.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Artemis-Hunt/ped#6

### LINKED ISSUE #125: [PE-D] Inputting a name with a slash causes characters before/after the slash to be ignored
-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Artemis-Hunt/ped#10

### LINKED ISSUE #126: [PE-D] 'calculate carbs" does not work
Annoying to type out full word i.e. carbohydrate

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Artemis-Hunt/ped#11

### LINKED ISSUE #127: [PE-D] calculate <nutrient> seems to exhibit weird behaviour
When a legit nutrient is included in an invalid string it prints fat only.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Artemis-Hunt/ped#12

### LINKED ISSUE #129: [PE-D] User's Name Can Be Empty
Entering a blank string after "name" continues the program. Steps to reproduce bug:
1. Start the program.
2. Type "name" followed by multiple whitespaces and enter.

User guide says that when using "editinfo", the name parameter cannot be empty. However, an empty name can still be entered. Steps to reproduce bug:
1. Start the program and enter the name and info as per normal.
2. Type "editinfo n/" followed by whitespace characters and enter.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ychong032/ped#2

### LINKED ISSUE #130: [PE-D] editinfo: Empty parameter crashes program
When using the "editinfo" command, if one of the parameters is empty, an unhandled exception arises. Steps to reproduce bug:
1. Start program and enter name and info as per normal.
2. Type "editinfo" followed by an empty parameter. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ychong032/ped#3

### LINKED ISSUE #131: [PE-D] Error message does not match user guide
The user guide states a maximum height and weight that the user is allowed to enter. However, the error messages displayed by the program are different. For example, the maximum height and weight in the user guide are 300cm and 500kg, respectively, while the program's error messages state 273cm and 443kg, respectively. Steps to reproduce bugs:
1. Start program and enter user name and info as per normal.
2. Type "editinfo h/301" and enter.
3. Type "editinfo c/501" and enter.

User guide:

Program:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ychong032/ped#4

### LINKED ISSUE #139: [PE-D] NumberFormatException for integer parameters
`NumberFormatException` when setting integer parameters with invalid input.

```
editinfo o/4294967296
Exception in thread "main" java.lang.NumberFormatException: For input string: "4294967296"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at seedu.dietbook.parser.Parser.executeEditInfo(Parser.java:293)
	at seedu.dietbook.command.EditInfoCommand.execute(EditInfoCommand.java:22)
	at seedu.dietbook.DietBook.main(DietBook.java:114)
```

This happens for `a/`, `h/`, `o/`, `c/`, `t/` for the `editinfo` command.

Also happens in the `add` command.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: daniellimws/ped#6

### PR DESCRIPTION
**Pull request by tikimonarch**
-Catching all exception
-Fixed for specific exceptions
-Fixed calculate rubbish acceptance
-Fixed name accepting empty/empty checker

### CODE REVIEW

File: src/main/java/seedu/dietbook/DietBook.java [hunk 1]
```diff
@@ -114,6 +114,8 @@ public static void main(String[] args) {
                 c.execute(dietBook.manager, dietBook.ui);
             } catch (DietException e) {
                 dietBook.ui.printErrorMessage(e.getMessage());
+            } catch (Exception e) {
+                throw new DietException("Wrong command format!");
```
Comment (HengFuYuen) [inline src/main/java/seedu/dietbook/DietBook.java]: Perhaps consider changing to a more generic message.

File: src/main/java/seedu/dietbook/checker/InputChecker.java [hunk 2]
```diff
@@ -247,9 +247,9 @@ public static void checkGender(String userInput) throws DietException {
      */
     public static void checkAgeLimit(int age) throws DietException {
         if (age < 0) {
-            throw new DietException("Input value cannot be less than 0!");
+            throw new DietException("Age value cannot be less than 0!");
         } else if (age > AGE_CAP) {
-            throw new DietException("Input value cannot be more than 125!");
+            throw new DietException("Age value cannot be more than 125!");
```
Comment (HengFuYuen) [inline src/main/java/seedu/dietbook/checker/InputChecker.java]: Perhaps consider changing 125 to AGE_CAP or 150. You might like to consider this suggestion for the other methods as well.

**Review by HengFuYuen — COMMENTED** [review]
Perhaps some minor changes needed.

File: src/main/java/seedu/dietbook/DietBook.java (hunk 1 above)
Comment (tikimonarch) [reply src/main/java/seedu/dietbook/DietBook.java]: I feel like this is super generic already because all the input are all "commands" so any typos should be safe to consider as a wrong format of command. "Something went wrong" is too vague of a message i feel? wdyt

Comment (HengFuYuen) [reply src/main/java/seedu/dietbook/DietBook.java]: I see. I was thinking that since all the exceptions are being caught here it could also possibly be catching an error from elsewhere in the system other than the command input. However, if you think that only the command input is likely to result in an exception that is caught here I think you can leave it as such.

Comment (tikimonarch) [reply src/main/java/seedu/dietbook/DietBook.java]: Hmm runtime error and such rite,,,, orite i will just change it to Something went wrong cos i think we will be catching most of the exceptions for commands.

**Review by HengFuYuen — COMMENTED** [review]
Perhaps consider closing the relevant issues reported in the PE dry run when merging this.
Current commit LGTM.

**Review by HengFuYuen — APPROVED** [review]

File: src/main/java/seedu/dietbook/DietBook.java (hunk 1 above)
Comment (HengFuYuen) [reply src/main/java/seedu/dietbook/DietBook.java]: Perhaps you can consider catching other possible generic exceptions that may be thrown like NumberFormatException, StringIndexOutOfBound, IOException before catching Exception so that more specific error messages can be output.
